name:                prosper
version:             0.1.0.0
github:              "ksilin/prosper"
license:             BSD3
author:              "ksilin"
maintainer:          "example@example.com"
copyright:           "2018 Konstantin Silin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/prosper#readme>

dependencies:
- base >= 4.7 && < 5
- Spock >= 0.13.0.0
- Spock-core >= 0.13.0.0
- reroute >= 0.5.0.0
- aeson >= 1.4.0.0
- text >= 1.2.3.0


library:
  source-dirs: src

executables:
  prosper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prosper

tests:
  prosper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prosper
